config/routes.rb
Rails.application.routes.draw do
  root "postcode_areas#new"

  resource :postcode_area, only: %i[new create]
end

app/models/postcode_area.rb
# frozen_string_literal: true

class PostcodeArea < OpenStruct
  include ActiveModel::Validations

  validates_with PostcodeValidator

  # Overload the `<<` operator to update the attributes using the `<<` syntax
  #
  # @param hash [Hash] a key value hash of values to be updated
  # @return [PostcodeArea]
  #
  # @usage PostcodeArea.new(postcode: "BN3 1AB) << { postcode: "SH24 999" }
  def <<(hash = {})
    hash.each_pair { |field, value| send("#{field}=", value) }

    self
  end

  protected

  # Overload the setter to ensure that our postcode is stripped of leading/trailing whitespace when its updated.
  # This is called from within the :<< method so when we update our instance with user data, it should remove any
  # whitespace.
  #
  # @param postcode [String]
  # @return void
  def postcode=(postcode)
    self[:postcode] = postcode.strip
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/postcode_areas_controller.rb
# frozen_string_literal: true

class PostcodeAreasController < ApplicationController
  def create
    # Update our postcode area with the data from the form
    postcode_area << permitted_params

    # Perform basic validation on the postcode to ensure its ready to be sent to the API
    @result = if postcode_area.valid?
                t("postcode_area.service_area.result.#{service_area_status}")
              else
                t("postcode_area.postcode.invalid")
              end

    render :new
  end

  def postcode_area
    @postcode_area ||= PostcodeArea.new
  end
  helper_method :postcode_area

  protected

  # Perform the API request and validate the resulting data
  def service_area_status
    Sh24::Postcode::ApiReader.new(postcode_area).perform

    ServiceAreaValidator.new(postcode_area).service_area? ? "in" : "out"
  end

  def permitted_params
    params.require(:postcode_area).permit(:postcode)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/postcode_areas/_form.html.erb
<div class="row">
	<%= form_with model: postcode_area, url: postcode_area_path, id: "postcode_area", class: "col-md-12 mt-5 mb-5" do |f| %>
		<div class="mb-3">
			<%= f.label :postcode, class: "form-label" %>
			<%= f.text_field :postcode, class: "form-control" %>
			<div class="form-text"><%= t("postcode_area.form.input.postcode.help_text") %></div>
		</div>

		<%= f.submit "Submit", class: "btn btn-primary" %>
		<%= link_to "Reset", root_path, class: "btn btn-default" %>
	<% end %>
</div>

app/views/postcode_areas/new.html.erb
<div class="container mt-5">
	<div class="row">
		<div class="col-md-2"></div>

		<div class="col-md-8">
			<h1><%= t("postcode_area.new.heading") %></h1>
			<p><%= t("postcode_area.new.intro") %></p>

			<%= render "form", postcode_area: postcode_area %>

			<% if @result.present? %>
				<div class="card mb-3">
					<div class="card-header">
						<%= t("postcode_area.service_area.result.title", postcode: postcode_area.postcode) %>
					</div>
					<div class="card-body">
						<%= @result %>
					</div>
				</div>
			<% end %>
		</div>

		<div class="col-md-2"></div>
	</div>
</div>